DROP TABLE IF EXISTS picture;
CREATE TABLE picture (
	id_picture SERIAL PRIMARY KEY,
	file_name VARCHAR(255) NOT NULL,
	hash VARCHAR(40) NOT NULL DEFAULT '',
	exif JSONB NOT NULL DEFAULT '{}'::jsonb,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT 'NOW()'
);
